name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: garyedwardhughes/ubuntu-fix8
    steps:
    - uses: actions/checkout@v2
    - name: Build Clang
      run: ./build_clang.sh


